services:
  hemovida.api:
    image: ${DOCKER_REGISTRY-}hemovidaapi
    build:
      context: .
      dockerfile: HemoVida.API/Dockerfile
    depends_on:
      - sqlserver
  
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    hostname: 'sqlserver'
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: "Numsey#2024"
    volumes:
      - c:\dados\volumes\mssql:/var/opt/mssql3
    ports:
      - '11433:1433'
    expose:
      - 1433
