services:
  hemovida.api:
    image: ${DOCKER_REGISTRY-}hemovidaapi
    build:
      context: .
      dockerfile: HemoVida.API/Dockerfile

  hemovida.sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: hemovida_sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql
  
  redis:
    image: redis:latest
    container_name: hemovida_redis
    ports:
      - "6379:6379"

volumes:
  sqlserverdata: