services:
  hemovida.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_SKIP_TLS_VALIDATION=true
      - ASPNETCORE_URLS=https://+:8081;http://+:80
    ports:
      - "32033:80"
      - "32034:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro