name: Docker Compose CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-test-analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Restaurar pacotes NuGet
        run: dotnet restore HemoVida.API/HemoVida.API.csproj

      - name: Build da solução
        run: dotnet build --no-restore --configuration Release HemoVida.API/HemoVida.API.csproj

      - name: Executar testes
        run: dotnet test --no-build --configuration Release --verbosity normal HemoVida.API/HemoVida.API.csproj

      - name: Análise com SonarCloud
        uses: SonarSource/sonarcloud-github-action@master
        with:
          projectBaseDir: .
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build e up com Docker Compose
        run: docker compose -f docker-compose.yml up -d --build

      - name: Aguardar serviços iniciarem
        run: sleep 30

      - name: Verificar containers em execução
        run: docker ps

      - name: Derrubar containers
        if: always()
        run: docker compose -f docker-compose.yml down
